# Generated by Django 3.1.3 on 2021-04-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='Vigencia',
        ),
    ]
