# Generated by Django 3.1.3 on 2021-04-06 23:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Orden a nombre de')),
                ('Status', models.CharField(choices=[('sí', 'Sí'), ('no', 'No')], default='sí', max_length=2, verbose_name='Pedido Para Llevar')),
                ('Domicilio', models.TextField(blank=True, null=True)),
                ('Celular', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="El número de celular debe comenzar con '55' y tener al menos 10 digitos.         Ejemplo: 5534325917", regex='55[0-9]{8}$')])),
                ('Email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message="Verifique que haya ingresado        de forma correcta su correo. Solo se aceptan correos de 'gmail', 'hotmail', 'outlook' y 'yahoo'.", regex='[\\.a-zA-Z0-9_-]*@(gmail|hotmail|outlook|yahoo)\\.(com|mx|live)\\w*')])),
                ('EmailVerificacion', models.EmailField(max_length=254, verbose_name='Email de Verificación')),
                ('Costo_Orden', models.FloatField(default=1, verbose_name='Costo Total del Pedido')),
                ('Orden_Lista', models.BooleanField(default=False, verbose_name='Orden Ya Lista')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Realización de la Orden')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización de la Orden')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': '1.Ordenes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenContenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Orden a Nombre de')),
                ('Email', models.EmailField(max_length=254)),
                ('Platillo_o_Bebida', models.CharField(max_length=100, verbose_name='Platillo o Bebida')),
                ('Cantidad_Alimento', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('Costo_Alimento', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Unitario')),
                ('Costo_Total_x_Alimento', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cantidad x Precio Unitario')),
                ('Titular_Orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_contenido', to='ordenes_y_pedidos.ordencliente')),
            ],
            options={
                'verbose_name': 'Contenido_Orden',
                'verbose_name_plural': '2.Contenido_Ordenes',
            },
        ),
    ]
