# Generated by Django 3.1.3 on 2021-04-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_y_pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencliente',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden', 'verbose_name_plural': '1.Ordenes'},
        ),
    ]
